- name: Install the {{ version }} version of firewalld
  yum:
    name: firewalld
    state: "{{ version }}"

- name: Start firewalld service
  service:
    name: firewalld
    state: started

- name: Enable firewalld service
  systemd:
    name: firewalld
    enabled: yes
