- name: Install the {{ httpd_version }} version of httpd (apache), php and php-mysql
  yum:
    name:
      - httpd
      - php
      - php-mysql
  update_cache: yes

- name: Configure firewall
  firewalld:
    permanent: yes
    port: "{{ httpd_port }}"
    immediate: yes # reload firewall after setting port
    state: enabled

- name: Start httpd service
  service:
    name: httpd
    state: started

- name: Copy configuration file (httpd.conf)
  copy:
    src: "{{ role_path }}/files/httpd.conf"
    dest: "{{ httpconf_path }}/httpd.conf"
    mode: 0777

- name: Enable httpd service
  systemd:
    name: httpd
    enabled: yes

- name: Install {{ git_version }} git version
  yum:
    name: git
    state: "{{ git_version }}"

- name: Create repository destination path if it doesn't exist
  file:
    path: "{{ repo_dest }}"
    state: directory
    mode: 0777

- name: Clone website git repository
  git:
    repo: "{{ web_gitrepo }}"
    dest: "{{ repo_dest }}"
    clone: yes
    force: yes

- name: Copy index.php file to web repository
  template:
    src: "index.php.j2"
    dest: "{{ repo_dest }}/index.php"
    mode: 0644

- name: Set httpd_can_network_connect_db flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes

- name: Test website is accesible
  uri:
    url: http://localhost
