httpd_port: 80/tcp

httpd_version: latest
php_version: latest
phpmysql_version: latest
git_version: latest

httpconf_path: /etc/httpd/conf
httpconf: httpd.conf
repo_dest: www/html

directoryindex: index.php
